#!/bin/bash
#testar entrada
if [ $# -ne 1 ]; then 
   echo "Uso do programa: $0 nome_do_arquivo"
   exit 1
fi

#obtem data de ultima modificacao do arquivo
data=$(stat -c %y $1)
data=${data%% *}
echo $data

#gerar nome do arquivo de saida
nomeSaida=$1
extensao=${nomeSaida##*.}
echo "extensao=$extensao"
nomeSaida=${nomeSaida%.*}
nomeSaida=$nomeSaida$(date +"_%y%m%d_%H%M")
echo "nomeSaida=$nomeSaida"

#converte o formato da data de yyyy-mm-dd para dd/mm/yyyy
texto=$(date --date=$data +"%d/%m/%y")
echo $texto

#usar o formato para usar o comando convert
executar="convert -pointsize 20 -fill yellow -gravity Southeast -draw 'text 20,20 \"$texto\"' $1 $nomeSaida.$extensao"
eval $executar
